// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/sonderkevin/governance/graph/model"
)

// CategoriaResolver is an autogenerated mock type for the CategoriaResolver type
type CategoriaResolver struct {
	mock.Mock
}

// Padre provides a mock function with given fields: ctx, obj
func (_m *CategoriaResolver) Padre(ctx context.Context, obj *model.Categoria) (*model.Categoria, error) {
	ret := _m.Called(ctx, obj)

	var r0 *model.Categoria
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Categoria) (*model.Categoria, error)); ok {
		return rf(ctx, obj)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Categoria) *model.Categoria); ok {
		r0 = rf(ctx, obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Categoria)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Categoria) error); ok {
		r1 = rf(ctx, obj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCategoriaResolver interface {
	mock.TestingT
	Cleanup(func())
}

// NewCategoriaResolver creates a new instance of CategoriaResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCategoriaResolver(t mockConstructorTestingTNewCategoriaResolver) *CategoriaResolver {
	mock := &CategoriaResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
