// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	domain "github.com/sonderkevin/governance/domain"
	mock "github.com/stretchr/testify/mock"
)

// CategoriaRepository is an autogenerated mock type for the CategoriaRepository type
type CategoriaRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: _a0
func (_m *CategoriaRepository) Delete(_a0 uint) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: _a0
func (_m *CategoriaRepository) Get(_a0 uint) (*domain.Categoria, error) {
	ret := _m.Called(_a0)

	var r0 *domain.Categoria
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.Categoria, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.Categoria); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Categoria)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: _a0
func (_m *CategoriaRepository) GetAll(_a0 *domain.CategoriaFilter) ([]*domain.Categoria, error) {
	ret := _m.Called(_a0)

	var r0 []*domain.Categoria
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.CategoriaFilter) ([]*domain.Categoria, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*domain.CategoriaFilter) []*domain.Categoria); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Categoria)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.CategoriaFilter) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: _a0
func (_m *CategoriaRepository) Save(_a0 *domain.Categoria) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Categoria) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: _a0
func (_m *CategoriaRepository) Update(_a0 *domain.Categoria) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Categoria) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCategoriaRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewCategoriaRepository creates a new instance of CategoriaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCategoriaRepository(t mockConstructorTestingTNewCategoriaRepository) *CategoriaRepository {
	mock := &CategoriaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
