// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	domain "github.com/sonderkevin/governance/domain"
	mock "github.com/stretchr/testify/mock"
)

// PermisoRepository is an autogenerated mock type for the PermisoRepository type
type PermisoRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0
func (_m *PermisoRepository) Get(_a0 uint) (*domain.Permiso, error) {
	ret := _m.Called(_a0)

	var r0 *domain.Permiso
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.Permiso, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.Permiso); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Permiso)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: _a0
func (_m *PermisoRepository) GetAll(_a0 *domain.PermisoFilter) ([]*domain.Permiso, error) {
	ret := _m.Called(_a0)

	var r0 []*domain.Permiso
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.PermisoFilter) ([]*domain.Permiso, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*domain.PermisoFilter) []*domain.Permiso); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Permiso)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.PermisoFilter) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPermisoRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewPermisoRepository creates a new instance of PermisoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPermisoRepository(t mockConstructorTestingTNewPermisoRepository) *PermisoRepository {
	mock := &PermisoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
