// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/sonderkevin/governance/graph/model"

	paging "github.com/nrfta/go-paging"
)

// PermisoResolver is an autogenerated mock type for the PermisoResolver type
type PermisoResolver struct {
	mock.Mock
}

// Grupos provides a mock function with given fields: ctx, obj, input, page
func (_m *PermisoResolver) Grupos(ctx context.Context, obj *model.Permiso, input *model.GrupoInput, page *paging.PageArgs) ([]*model.Grupo, error) {
	ret := _m.Called(ctx, obj, input, page)

	var r0 []*model.Grupo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Permiso, *model.GrupoInput, *paging.PageArgs) ([]*model.Grupo, error)); ok {
		return rf(ctx, obj, input, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Permiso, *model.GrupoInput, *paging.PageArgs) []*model.Grupo); ok {
		r0 = rf(ctx, obj, input, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Grupo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Permiso, *model.GrupoInput, *paging.PageArgs) error); ok {
		r1 = rf(ctx, obj, input, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Usuarios provides a mock function with given fields: ctx, obj, input, page
func (_m *PermisoResolver) Usuarios(ctx context.Context, obj *model.Permiso, input *model.UsuarioInput, page *paging.PageArgs) ([]*model.Usuario, error) {
	ret := _m.Called(ctx, obj, input, page)

	var r0 []*model.Usuario
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Permiso, *model.UsuarioInput, *paging.PageArgs) ([]*model.Usuario, error)); ok {
		return rf(ctx, obj, input, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Permiso, *model.UsuarioInput, *paging.PageArgs) []*model.Usuario); ok {
		r0 = rf(ctx, obj, input, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Usuario)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Permiso, *model.UsuarioInput, *paging.PageArgs) error); ok {
		r1 = rf(ctx, obj, input, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPermisoResolver interface {
	mock.TestingT
	Cleanup(func())
}

// NewPermisoResolver creates a new instance of PermisoResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPermisoResolver(t mockConstructorTestingTNewPermisoResolver) *PermisoResolver {
	mock := &PermisoResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
