package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.27

import (
	"context"

	"github.com/nrfta/go-paging"
	"github.com/sonderkevin/governance/graph/generated"
	"github.com/sonderkevin/governance/graph/model"
)

// Permisos is the resolver for the permisos field.
func (r *grupoResolver) Permisos(ctx context.Context, obj *model.Grupo, input *model.PermisoInput, page *paging.PageArgs) ([]*model.Permiso, error) {
	return r.PermisoService.GetAll(&model.PermisoInput{GrupoID: &obj.ID})
}

// Usuarios is the resolver for the usuarios field.
func (r *grupoResolver) Usuarios(ctx context.Context, obj *model.Grupo, input *model.UsuarioInput, page *paging.PageArgs) ([]*model.Usuario, error) {
	return r.UsuarioService.GetAll(&model.UsuarioInput{GrupoID: &obj.ID})
}

// Grupo returns generated.GrupoResolver implementation.
func (r *Resolver) Grupo() generated.GrupoResolver { return &grupoResolver{r} }

type grupoResolver struct{ *Resolver }
